configured_endpoints: 39
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/new%2Fblockaid-0bbb4ff170ce76aa6247ed0c0d84dd4321fecffe93ca6c6edfc0d3f93db7dd9a.yml
openapi_spec_hash: 8c212d4c717da6632b3d38b146f1fd29
config_hash: 7ca1322392fafe8b8b3fcf5cb54ec02f
